# Generated by Django 4.2.5 on 2023-09-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_item_amount_alter_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=None, help_text='Amount of Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Armor', 'Armor'), ('Boots', 'Boots'), ('Helmet', 'Helmet'), ('Ingredients', 'Ingredients'), ('Item', 'Item'), ('Potion', 'Potion'), ('Relic', 'Relic'), ('Stone', 'Stone'), ('Weapon', 'Weapon')], default='Weapon', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(help_text='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='grade',
            field=models.CharField(choices=[('Common', 'Common'), ('Epic', 'Epic'), ('God', 'God'), ('Legendary', 'Legendary'), ('Mythical', 'Mythical'), ('Rare', 'Rare'), ('Unique', 'Unique')], default='Common', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Item Name', max_length=255),
        ),
    ]
